name: WorldDefend
version: 0.0.2
api: 5.0.0
main: taylordevs\WorldDefend\Loader
author: taylordevs
description: A plugin for PMMP that will defend the worlds
website: https://github.com/taylordevs/WorldDefend

permissions:
    worlddefend.command:
        description: Allows the player to use the command
        default: true
